INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ADL', 'Kabupaten Konawe Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AFT', 'Kabupaten Maybrat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AGM', 'Kabupaten Bengkulu Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AGT', 'Kabupaten Asmat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AKK', 'Kabupaten Labuhanbatu Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AMB', 'Kota Ambon', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AMR', 'Kabupaten Minahasa Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AMS', 'Kabupaten Sorong', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'AMT', 'Kabupaten Hulu Sungai Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'APN', 'Kabupaten Tojo Una Una', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ARM', 'Kabupaten Minahasa Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ARS', 'Kabupaten Solok', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ATB', 'Kabupaten Belu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BAA', 'Kabupaten Rote Ndao', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BAN', 'Kabupaten Bantaeng', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BAR', 'Kabupaten Barru', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BAU', 'Kota Bau Bau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BBS', 'Kabupaten Brebes', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BBU', 'Kabupaten Way Kanan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BDG', 'Kota Bandung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BDL', 'Kota Bandar Lampung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BDW', 'Kabupaten  Bondowoso', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BEK', 'Kabupaten  Bengkayang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BEN', 'Kabupaten Kepulauan Selayar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BGK', 'Kabupaten Morowali', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BGL', 'Kota Bengkulu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BGR', 'Kota Bogor', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BHN', 'Kabupaten Kaur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BIK', 'Kabupaten Biak Numfor', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BIM', 'Kota Bima', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BIR', 'Kabupaten Bireuen', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BIT', 'Kota Bitung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BJB', 'Kota Banjarbaru', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BJM', 'Kota Banjarmasin', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BJN', 'Kabupaten  Bojonegoro', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BJR', 'Kota Banjar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BJW', 'Kabupaten Ngada', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BKJ', 'Kabupaten Gayo Lues', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BKL', 'Kabupaten Bangkalan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BKN', 'Kabupaten Kampar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BKO', 'Kabupaten Merangin', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BKS', 'Kota Bekasi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BKT', 'Kota Bukittinggi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLA', 'Kabupaten Blora', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLG', 'Kabupaten Toba Samosir', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLI', 'Kabupaten Bangli', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLK', 'Kabupaten  Bulukumba', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLN', 'Kabupaten Tanah Bumbu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLS', 'Kabupaten Bengkalis', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLT', 'Kota Blitar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BLU', 'Kabupaten Bolaang Mongondow Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BNA', 'Kota Banda Aceh', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BNG', 'Kabupaten Buton Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BNJ', 'Kota Binjai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BNR', 'Kabupaten  Banjarnegara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BNT', 'Kabupaten Barito Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BON', 'Kota Bontang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BPD', 'Kabupaten Aceh Barat Daya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BPP', 'Kota Balikpapan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BRB', 'Kabupaten Hulu Sungai Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BRG', 'Kabupaten Manggarai Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BRK', 'Kabupaten Bolaang Mongondow Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BRM', 'Kabupaten Mamberamo Raya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BSB', 'Kabupaten Bintan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BSK', 'Kabupaten Tanah Datar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BTA', 'Kabupaten Ogan Komering Ulu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BTG', 'Kabupaten Batang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BTI', 'Kabupaten Teluk Bintuni', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BTL', 'Kabupaten Bantul', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BTM', 'Kota Batam', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BTU', 'Kota Batu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BTW', 'Kabupaten Waropen', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BUL', 'Kabupaten Buol', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BYL', 'Kabupaten Boyolali', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'BYW', 'Kabupaten  Banyuwangi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CAG', 'Kabupaten Aceh Jaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CBI', 'Kabupaten Bogor', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CBN', 'Kota Cirebon', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CJR', 'Kabupaten Cianjur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CKG', 'Kota Adm. Jakarta Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CKR', 'Kabupaten Bekasi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CLG', 'Kota Cilegon', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CLP', 'Kabupaten Cilacap', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CMH', 'Kota Cimahi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CMS', 'Kabupaten Ciamis', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CPT', 'Kota Tangerang Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'CRP', 'Kabupaten Rejang Lebong', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DGL', 'Kabupaten Donggala', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DKL', 'Kabupaten Lingga', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DLS', 'Kabupaten Humbang Hasundutan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DMK', 'Kabupaten Demak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DOB', 'Kabupaten Kepulauan Aru', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DPK', 'Kota Depok', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DPR', 'Kota Denpasar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DPU', 'Kabupaten Dompu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DRH', 'Kabupaten Seram Bagian Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DTH', 'Kabupaten Seram Bagian Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'DUM', 'Kota Dumai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ELL', 'Kabupaten Yalimo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'END', 'Kabupaten Ende', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ENR', 'Kabupaten Enrekang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ERT', 'Kabupaten Paniai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'FEF', 'Kabupaten Tambrauw', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'FFK', 'Kabupaten Fak Fak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GDT', 'Kabupaten  Pesawaran', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GGP', 'Kota Adm. Jakarta Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GIN', 'Kabupaten Gianyar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GNS', 'Kabupaten Lampung Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GNT', 'Kabupaten Padang Lawas Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GRG', 'Kabupaten Lombok Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GRT', 'Kabupaten Garut', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GSK', 'Kabupaten Gresik', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GST', 'Kabupaten Nias', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'GTO', 'Kabupaten Gorontalo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'IDL', 'Kabupaten Ogan Ilir', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'IDM', 'Kabupaten  Indramayu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ILG', 'Kabupaten Puncak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JAP', 'Kabupaten Jayapura', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JBG', 'Kabupaten Jombang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JLL', 'Kabupaten Halmahera Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JMB', 'Kota Jambi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JMR', 'Kabupaten Jember', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JNP', 'Kabupaten  Jeneponto', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JPA', 'Kabupaten Jepara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'JTH', 'Kabupaten Aceh Besar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KAG', 'Kabupaten Ogan Komering Ilir', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KBA', 'Kabupaten Bangka Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KBG', 'Kabupaten Tolikara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KBJ', 'Kabupaten Karo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KBK', 'Kabupaten Mamberamo Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KBM', 'Kabupaten Kebumen', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KBR', 'Kabupaten Kotabaru', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KDI', 'Kota Kendari', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KDL', 'Kabupaten Kendal', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KDR', 'Kabupaten Kediri', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KDS', 'Kabupaten Kudus', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KEP', 'Kabupaten Mappi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KFM', 'Kabupaten Timor Tengah Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KGM', 'Kabupaten Dogiyai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KGN', 'Kabupaten Hulu Sungai Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KIS', 'Kabupaten Asahan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KJN', 'Kabupaten  Pekalongan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KKA', 'Kabupaten Kolaka', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KKN', 'Kabupaten Gunung Mas', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KLA', 'Kabupaten Lampung Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KLB', 'Kabupaten Alor', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KLK', 'Kabupaten Kapuas', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KLN', 'Kabupaten Klaten', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KLP', 'Kabupaten Seruyan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KLT', 'Kabupaten Tanjung Jabung Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KMN', 'Kabupaten Kaimana', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KNG', 'Kabupaten Kuningan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KNR', 'Kabupaten Blitar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KOT', 'Kabupaten  Tanggamus', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KPG', 'Kabupaten Kupang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KPH', 'Kabupaten Kepahiang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KPI', 'Kabupaten Labuhanbatu Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KPN', 'Kabupaten Malang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KRA', 'Kabupaten  Karangasem', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KRB', 'Kabupaten Aceh Tamiang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KRG', 'Kabupaten  Karanganyar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KRS', 'Kabupaten  Probolinggo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KRT', 'Kabupaten Bengkulu Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KSN', 'Kabupaten Katingan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KSU', 'Kabupaten Adm. Kepulauan Seribu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KTB', 'Kabupaten Lampung Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KTG', 'Kota Kotamobagu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KTN', 'Kabupaten Aceh Tenggara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KTP', 'Kabupaten Ketapang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KWD', 'Kabupaten Gorontalo Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KWG', 'Kabupaten Karawang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KYB', 'Kota Adm. Jakarta Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'KYM', 'Kabupaten Nduga', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LBA', 'Kabupaten Halmahera Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LBB', 'Kabupaten Agam', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LBJ', 'Kabupaten Manggarai Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LBP', 'Kabupaten Deli Serdang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LBS', 'Kabupaten Pasaman', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LGS', 'Kabupaten Aceh Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LHM', 'Kabupaten Nias Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LHT', 'Kabupaten Lahat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LIW', 'Kabupaten Lampung Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LLG', 'Kota Lubuk Linggau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LLK', 'Kabupaten Bolaang Mongondow', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LMG', 'Kabupaten  Lamongan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LMJ', 'Kabupaten Lumajang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LMP', 'Kabupaten Batu Bara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LRT', 'Kabupaten Flores Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LSK', 'Kabupaten Aceh Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LSM', 'Kota Lhokseumawe', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LSS', 'Kabupaten Kolaka Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LTU', 'Kabupaten Nias Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LWK', 'Kabupaten Banggai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'LWL', 'Kabupaten Lembata', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MAB', 'Kabupaten Halmahera Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MAD', 'Kota Madiun', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MAK', 'Kabupaten Tana Toraja', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MAM', 'Kabupaten Mamuju', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MAR', 'Kabupaten Pahuwato', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MBL', 'Kabupaten Musi Rawas', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MBN', 'Kabupaten Batanghari', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MBO', 'Kabupaten Aceh Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MBY', 'Kabupaten Nagekeo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MDN', 'Kota Medan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MET', 'Kota Metro', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MGG', 'Kota Magelang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MGL', 'Kabupaten Tulang Bawang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MGN', 'Kabupaten Kepulauan Talaud', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MGR', 'Kabupaten Belitung Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MGT', 'Kabupaten Magetan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MGW', 'Kabupaten Badung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MJK', 'Kabupaten Mojokerto', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MJL', 'Kabupaten  Majalengka', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MJN', 'Kabupaten Majene', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MJY', 'Kabupaten Madiun', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MKD', 'Kabupaten Magelang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MKM', 'Kabupaten Muko Muko', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MKS', 'Kota Makassar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MLG', 'Kota Malang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MLL', 'Kabupaten Luwu Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MLN', 'Kabupaten Malinau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MME', 'Kabupaten Sikka', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MMS', 'Kabupaten Mamasa', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MNA', 'Kabupaten Bengkulu Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MND', 'Kota Manado', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MNK', 'Kabupaten Manokwari', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MPR', 'Kabupaten Oku Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MPW', 'Kabupaten Pontianak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRB', 'Kabupaten Bungo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRD', 'Kabupaten Oku Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRE', 'Kabupaten Muara Enim', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRH', 'Kabupaten Barito Kuala', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRJ', 'Kabupaten Sijunjung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRK', 'Kabupaten Merauke', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRN', 'Kabupaten Pidie Jaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRS', 'Kabupaten Maros', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MRT', 'Kabupaten Tebo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MSB', 'Kabupaten Luwu Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MSH', 'Kabupaten Maluku Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MSJ', 'Kabupaten Mesuji', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MSK', 'Kabupaten Tanjung Jabung Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MTK', 'Kabupaten Bangka Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MTP', 'Kabupaten Banjar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MTR', 'Kota Mataram', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MTS', 'Kabupaten Pulau Morotai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MTW', 'Kabupaten Barito Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'MUL', 'Kabupaten Puncak Jaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NAB', 'Kabupaten Nabire', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NBA', 'Kabupaten Landak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NGA', 'Kabupaten Jembrana', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NGB', 'Kabupaten  Lamandau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NGP', 'Kabupaten Melawi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NGW', 'Kabupaten Ngawi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NJK', 'Kabupaten Nganjuk', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NLA', 'Kabupaten Buru', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NMR', 'Kabupaten Buru Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NNK', 'Kabupaten Nunukan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NPH', 'Kabupaten Bandung Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'NPM', 'Kabupaten Padang Pariaman', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'ODS', 'Kabupaten Kepulauan Siau Tagulandang Biaro', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'OSB', 'Kabupaten Pegunungan Bintang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PAD', 'Kota Padang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PAL', 'Kota Palu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PBG', 'Kabupaten  Purbalingga', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PBL', 'Kota Probolinggo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PBM', 'Kota Prabumulih', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PBR', 'Kota Pekanbaru', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PBU', 'Kabupaten Kotawaringin Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PCT', 'Kabupaten Pacitan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PDA', 'Kabupaten Solok Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PDG', 'Kabupaten  Pandeglang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PDP', 'Kota Padang Panjang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PGA', 'Kota Pagar Alam', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PGP', 'Kota Pangkal Pinang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PIN', 'Kabupaten Pinrang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PKB', 'Kabupaten Banyuasin', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PKJ', 'Kabupaten Pangkajene Kepulauan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PKK', 'Kabupaten Pelalawan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PKL', 'Kota Pekalongan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PKY', 'Kabupaten Mamuju Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PLG', 'Kota Palembang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PLI', 'Kabupaten Tanah Laut', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PLJ', 'Kabupaten  Dharmasraya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PLK', 'Kota Palangkaraya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PLP', 'Kabupaten Luwu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PLW', 'Kabupaten Polewali Mandar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PMK', 'Kabupaten  Pamekasan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PML', 'Kabupaten Pemalang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PMN', 'Kota Pariaman', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PMS', 'Kabupaten  Simalungun', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PNG', 'Kabupaten Ponorogo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PNJ', 'Kabupaten Penajam Paser Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PNN', 'Kabupaten Pesisir Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PPS', 'Kabupaten Pulang Pisau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PRC', 'Kabupaten Murung Raya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PRE', 'Kota Pare Pare', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PRG', 'Kabupaten Parigi Moutong', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PRN', 'Kabupaten Balangan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PRP', 'Kabupaten Rokan Hulu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PRR', 'Kabupaten Samosir', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PRW', 'Kabupaten Pringsewu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PSN', 'Kota Pasuruan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PSO', 'Kabupaten Poso', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PSP', 'Kabupaten Tapanuli Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PSR', 'Kabupaten Pasuruan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PSW', 'Kabupaten Buton', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PTI', 'Kabupaten Pati', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PTK', 'Kota Pontianak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PTS', 'Kabupaten Kapuas Hulu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PWD', 'Kabupaten Grobogan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PWK', 'Kabupaten  Purwakarta', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PWR', 'Kabupaten Purworejo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PWT', 'Kabupaten Banyumas', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PYA', 'Kabupaten Lombok Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PYB', 'Kabupaten Mandailing Natal', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'PYH', 'Kota Payakumbuh', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RAH', 'Kabupaten Muna', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RAN', 'Kabupaten Natuna', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RAP', 'Kabupaten  Labuhanbatu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RAS', 'Kabupaten Teluk Wondama', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RBG', 'Kabupaten Rembang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RGT', 'Kabupaten Indragiri Hulu', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RKB', 'Kabupaten Lebak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RMB', 'Kabupaten Bombana', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RTA', 'Kabupaten Tapin', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RTG', 'Kabupaten Manggarai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RTN', 'Kabupaten Minahasa Tenggara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'RTP', 'Kabupaten Toraja Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SAB', 'Kota Sabang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SAG', 'Kabupaten Sanggau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SAK', 'Kabupaten Siak', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SAL', 'Kabupaten Pakpak Bharat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBB', 'Kabupaten Sabu Raijua', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBG', 'Kabupaten Tapanuli Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBH', 'Kabupaten Padang Lawas', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBM', 'Kabupaten Sukabumi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBR', 'Kabupaten Cirebon', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBS', 'Kabupaten Sambas', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBW', 'Kabupaten Sumbawa', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SBY', 'Kota Surabaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SDA', 'Kabupaten Sidoarjo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SDK', 'Kabupaten Dairi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SDN', 'Kabupaten Lampung Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SDR', 'Kabupaten Sidenreng Rappang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SDW', 'Kabupaten Kutai Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SED', 'Kabupaten Sekadau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SEL', 'Kabupaten Lombok Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGB', 'Kabupaten Sigi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGI', 'Kabupaten Pidie', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGL', 'Kabupaten Bangka', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGM', 'Kabupaten Gowa', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGN', 'Kabupaten Sragen', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGP', 'Kabupaten Intan Jaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGR', 'Kabupaten Buleleng', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SGT', 'Kabupaten Kutai Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SIT', 'Kabupaten Situbondo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKB', 'Kota Sukabumi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKD', 'Kabupaten Kayong Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKG', 'Kabupaten Wajo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKH', 'Kabupaten Sukoharjo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKL', 'Kabupaten Aceh Singkil', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKM', 'Kabupaten Nagan Raya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKN', 'Kabupaten Banggai Kepulauan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKR', 'Kabupaten Sukamara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKT', 'Kota Surakarta', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKW', 'Kota Singkawang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SKY', 'Kabupaten Musi Banyuasin', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SLK', 'Kota Solok', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SLT', 'Kota Salatiga', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SLW', 'Kabupaten Tegal', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SMD', 'Kabupaten Sumedang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SMG', 'Kota Semarang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SMH', 'Kabupaten Yahukimo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SMI', 'Kabupaten Sarmi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SML', 'Kabupaten Maluku Tenggara Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SMN', 'Kabupaten Sleman', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SMP', 'Kabupaten Sumenep', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SMR', 'Kota Samarinda', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SNB', 'Kabupaten Simeulue', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SNG', 'Kabupaten Subang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SNJ', 'Kabupaten Sinjai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SNN', 'Kabupaten Kepulauan Sula', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SNT', 'Kabupaten Muaro Jambi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SOE', 'Kabupaten Timor Tengah Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SON', 'Kota Sorong', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SOR', 'Kabupaten Bandung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SPA', 'Kabupaten  Tasikmalaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SPE', 'Kabupaten Pasaman Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SPG', 'Kabupaten Sampang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SPN', 'Kabupaten Kerinci', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SPT', 'Kabupaten Kotawaringin Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRG', 'Kabupaten Serang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRH', 'Kabupaten Serdang Bedagai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRK', 'Kabupaten Lima Puluh Kota', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRL', 'Kabupaten  Sarolangun', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRP', 'Kabupaten Klungkung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRU', 'Kabupaten Kepulauan Yapen', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRW', 'Kabupaten Supiori', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SRY', 'Kabupaten Kubu Raya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'STB', 'Kabupaten Langkat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'STG', 'Kabupaten Sintang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'STR', 'Kabupaten Bener Meriah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SUS', 'Kota Subulussalam', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SWL', 'Kota Sawahlunto', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'SWW', 'Kabupaten Bone Bolango', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TAB', 'Kabupaten Tabanan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TAM', 'Kabupaten Sumba Barat Daya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TAR', 'Kota Tarakan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TAS', 'Kabupaten Seluma', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TBG', 'Kabupaten Empat Lawang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TBH', 'Kabupaten Indragiri Hilir', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TBK', 'Kabupaten Karimun', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TBL', 'Kabupaten Bangka Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TBN', 'Kabupaten Tuban', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TBT', 'Kota Tebing Tinggi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TDN', 'Kabupaten Belitung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TDP', 'Kabupaten Tana Tidung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TDR', 'Kota Tidore Kepulauan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TGL', 'Kota Tegal', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TGR', 'Kabupaten Tangerang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TGT', 'Kabupaten Paser', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'THN', 'Kabupaten Kepulauan Sangihe', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TIG', 'Kabupaten Deiyai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TIM', 'Kabupaten Mimika', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TJB', 'Kota Tanjung Balai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TJG', 'Kabupaten Tabalong', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TJN', 'Kabupaten Lombok Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TJP', 'Kota Adm. Jakarta Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TJS', 'Kabupaten Bulungan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TKA', 'Kabupaten Takalar', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TKN', 'Kabupaten Aceh Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TKR', 'Kabupaten Maluku Barat Daya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TLD', 'Kabupaten Nias Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TLG', 'Kabupaten  Tulungagung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TLI', 'Kabupaten Toli Toli', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TLK', 'Kabupaten Kuantan Singingi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TLW', 'Kabupaten Sumbawa Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TMB', 'Kabupaten Sorong Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TMG', 'Kabupaten  Temanggung', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TMH', 'Kota Tomohon', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TML', 'Kabupaten Barito Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TMR', 'Kabupaten Boven Digoel', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TMT', 'Kabupaten Boalemo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TNA', 'Kota Adm. Jakarta Pusat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TNG', 'Kota Tangerang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TNN', 'Kabupaten Minahasa', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TNR', 'Kabupaten Berau', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TOB', 'Kabupaten Halmahera Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TOM', 'Kabupaten Lanny Jaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TPG', 'Kota Tanjung Pinang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TPT', 'Kabupaten Kepulauan Mentawai', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TRG', 'Kabupaten Kutai Kertanegara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TRK', 'Kabupaten  Trenggalek', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TRP', 'Kabupaten Kepulauan Anambas', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TRT', 'Kabupaten Tapanuli Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TSM', 'Kota Tasikmalaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TTE', 'Kota Ternate', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TTG', 'Kabupaten Kepulauan Meranti', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TTN', 'Kabupaten Aceh Selatan', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TTY', 'Kabupaten Bolaang Mongondow Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TUB', 'Kabupaten Lebong', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TUL', 'Kabupaten Maluku Tenggara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'TWG', 'Kabupaten Tulang Bawang Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'UJT', 'Kabupaten Rokan Hilir', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'UNH', 'Kabupaten Konawe', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'UNR', 'Kabupaten Semarang', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WAM', 'Kabupaten  Jayawijaya', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WAS', 'Kabupaten Raja Ampat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WAT', 'Kabupaten Kulon Progo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WBL', 'Kabupaten Sumba Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WED', 'Kabupaten Halmahera Tengah', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WGD', 'Kabupaten Konawe Utara', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WGP', 'Kabupaten Sumba Timur', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WGW', 'Kabupaten Wakatobi', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WHO', 'Kabupaten Bima', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WKB', 'Kabupaten Sumba Barat', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WNG', 'Kabupaten Wonogiri', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WNO', 'Kabupaten Gunung Kidul', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WNS', 'Kabupaten Soppeng', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WRS', 'Kabupaten Keerom', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WSB', 'Kabupaten  Wonosobo', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'WTP', 'Kabupaten Bone', 1);
INSERT INTO `cities`(`code`,`name`, `country_id`) VALUES ( 'YYK', 'Kota Yogyakarta', 1);
